### PR TITLE
remove signup form

### LINKED ISSUE #26: Remove signup button from studio home page
We don't want users creating accounts by visiting studio and then accessing the register page. 

in xpro, we remove the "Sign Up" link from the index page on cms. We should do the same thing here. 

Compare: https://studio-rc.xpro.mit.edu/ to https://studio-qa.mitxonline.mit.edu/

### PR DESCRIPTION
**Pull request by umarmughal824**
fixes #26 

remove signup form

#### Screenshots

Screenshot 2022-01-26 at 17 04 30

Screenshot 2022-01-26 at 15 40 56

### CODE REVIEW

**Comment by briangrossman** [comment]
@umarmughal824 
This is looking good. 

I have a few questions.
- What is the difference between the two screenshots you shared above? Which one would a user see? 
- I assume you would substitute `MITx Online` for `Your Platform Name Here`. Is that correct?
- There is a typo on the blue button, it's missing the `e` in `MITx Online`
- In the top image, it's a little confusing that it says `Create an account using`, then it says `Login with MITx Onilne`

**Comment by umarmughal824** [comment]
> * What is the difference between the two screenshots you shared above? Which one would a user see?

@briangrossman The difference is that with no third-party auth it will show only a blank page as in the second image. Once you add a third-party authentication it will start listing down all of them as shown in the first screenshot.

And all of your other concerns are right because I have not properly configured it. All of them are configurables so you could configure them as per your requirements.

**Comment by briangrossman** [comment]
@umarmughal824 

Thank you. This looks fine to me. 

Where will the `Sign In` link and `MITx Online` button take you?

**Comment by umarmughal824** [comment]
> @umarmughal824
> 
> Thank you. This looks fine to me.
> 
> Where will the `Sign In` link and `MITx Online` button take you?

Sign In page redirects to /login page and MITx Online button redirects to Mit xOnline instance that is configurable.

**Comment by briangrossman** [comment]
@umarmughal824 

Thanks.

Ultimately, we want users to be redirected to pages on MITx Online whenever they need to Sign In or Register. 

When I try to access https://courses-qa.mitxonline.mit.edu/login, I am directed to:
- Not signed in: MITx Online to sign in, but then directed to the edX dashboard after signing in
- Signed in: the edX dashboard 
This is not desired behavior as we don't want learners going to their edX dashboard page. 

Is it possible to have both of these links simply take the learner to: https://mitxonline.mit.edu/ ? 

At that point, the learner can decide if they want to Sign In or Register. And that works well if they're already signed in, too.

**Comment by umarmughal824** [comment]
> * Signed in: the edX dashboard
>   This is not desired behavior as we don't want learners going to their edX dashboard page.

That specific issue is not a part of the theme instead it should be done in python code. So you can create an issue for it.

**Review by arslanashraf7 — APPROVED** [review]
👍

**Comment by briangrossman** [comment]
@umarmughal824 
> > * Signed in: the edX dashboard
> >   This is not desired behavior as we don't want learners going to their edX dashboard page.
> 
> That specific issue is not a part of the theme instead it should be done in python code. So you can create an issue for it.

Ok. If you are able to point both the `Sign In` link and the `MITx Online` button to https://mitxonline.mit.edu/, then this will resolve this concern.

**Comment by umarmughal824** [comment]
> @umarmughal824
> 
> > > * Signed in: the edX dashboard
> > >   This is not desired behavior as we don't want learners going to their edX dashboard page.
> > 
> > 
> > That specific issue is not a part of the theme instead it should be done in python code. So you can create an issue for it.
> 
> Ok. If you are able to point both the `Sign In` link and the `MITx Online` button to https://mitxonline.mit.edu/, then this will resolve this concern.

yeah that's why I have merged it

**Pull request merged**
