### PR TITLE
base_url and import errors fix

### PR DESCRIPTION
**Pull request by asadiqbal08**
fixes: #3 #4

### CODE REVIEW

**Comment by asadiqbal08** [comment]
@pdpinch I introduced a `koa` branch here that basically contains all the changes of `mitxpro-theme/koa` and thinking to merge changes in it. Do you have any concerns ?

**Comment by asadiqbal08** [comment]
`paver update_assets` command is stable now.

**Comment by pdpinch** [comment]
> I introduced a koa branch here that basically contains all the changes of mitxpro-theme/koa and thinking to merge changes in it. Do you have any concerns ?

I'm happy with whatever works, but I think you should merge it into the main branch. We won't be using this theme with koa, so calling it `koa` is misleading.

**Comment by asadiqbal08** [comment]
Ok

**Pull request closed without merging**
