### PR TITLE
feat: override proctoring requirements email

### PR DESCRIPTION
**Pull request by arslanashraf7**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [ ] Mobile width screenshots
- [x] Testing
  - [x] Code is tested
  - [ ] Changes have been manually tested
- [ ] Settings
  - [ ] New settings have reasonable development defaults, if applicable
  - [ ] Opened issue in the [ol-infrastructure repo](https://github.com/mitodl/ol-infrastructure/issues/new) for any necessary configuration changes to deployed environments

#### What are the relevant tickets?
https://github.com/mitodl/hq/issues/725

#### What's this PR do?
- Adds a template override for the proctoring requirements email that's sent when a user enrolls in a course that has proctoring enabled and has proctored exams in it.

#### How should this be manually tested?
There are two options to test this locally.

1. Setup Proctoring backend, Configure eCommerce
    - Follow the instructions on https://edx.readthedocs.io/projects/edx-partner-course-staff/en/latest/proctored_exams/proctored_enabling.html to enable proctored exams
    - Create a course mode with any of `Professional, Masters, Verified`
    - Setup the ecommerce things for the course https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/ecommerce/index.html
    - Configure email to work locally

2. If you are looking for a simpler way to test the PR (See below)
    - open `openedx/core/djangoapps/enrollments/api.py` and at line#591 add `CourseMode.HONOR` in the `appropriate_modes` list

(Common Steps)
- Setup this theme
- Create a course in the studio
- Create a course mode `Honor` (For testing so that we don't have to enable e-commerce functionality)
- in `Advanced Settings` enable `Enable Proctored Exams`
- In the course content, add a section/sub-section/unit and mark it as `Proctored` through the section grade setting
- Now enroll in this course
- check `/edx/src/ace_messages` directory you should see `*.datestamp.html` files for all the emails being sent.

#### Where should the reviewer start?
(Optional)

#### Any background context you want to provide?
(Optional)

#### Screenshots (if appropriate)
**Before**

image

**After**

image

### CODE REVIEW

**Comment by arslanashraf7** [comment]
I've setup a course https://rc.mitxonline.mit.edu/courses/course-v1:Arbisoft+ARB_TPC_1/  on Rc that can be used to test proctoring email for cross matching.

**Comment by pdpinch** [comment]
It seems like having a link to instructions and requirements would be good. Is there a reason why that's omitted in the screenshot?

**Comment by pdpinch** [comment]
Oh, nevermind. I see the comment from Shira when I asked for a link:  

> ➤ shira commented:
>
> pdpinch not really. All Proctoring Instructions and Requirements would be different dependent on the course team. I think we should probably just remove that link if we can.

**Comment by pdpinch** [comment]
Two more comments:

1. Will the broken image be fixed when we go to production?

2. The paragraphs are very close together. Can we add a line break or some other spacin?

**Comment by rachellougee** [comment]
The code and test look good. Just need to add some spacing for the <p> tag per Peter's comment.

**Comment by arslanashraf7** [comment]
> Two more comments:
> 
> 1. Will the broken image be fixed when we go to production?

Yes, This is a cdn/cloudfront url broken locally, but it should work fine on RC and Prod.


> 2. The paragraphs are very close together. Can we add a line break or some other spacin?

Yes, Added them, Updated the screenshot in the PR description. Could you please take a look and let me know if it looks good to you.

**Review by pdpinch — APPROVED** [review]
screenshots look good 👍

**Pull request merged**
