### PR TITLE
Koa changes from xPro to main

### LINKED ISSUE #2: Test with current devstack running master
Follow the installation instructions at https://github.com/mitodl/mitxonline-theme/blob/main/README.md and confirm that the theme can be deployed on devstack, with the master branch of edx-platform. 

You can tell if the theme was deployed by looking for the "Support Center" link in the footer. 

image

### PR DESCRIPTION
**Pull request by asadiqbal08**
fixes #2

### CODE REVIEW

**Comment by asadiqbal08** [comment]
@pdpinch you ok to merge ?

**Comment by asadiqbal08** [comment]
Let me just update the Readme references.

**Comment by pdpinch** [comment]
Will this fix #2 ?

**Comment by asadiqbal08** [comment]
My `paver update_assets` command is running successfully With this change set now.

Screen Shot 2021-08-13 at 5 47 26 PM

**Comment by asadiqbal08** [comment]
Let me confirm theme deployment locally.

**Comment by asadiqbal08** [comment]
I guess, theme changes are now applying locally. 

Screen Shot 2021-08-13 at 5 55 39 PM

**Review by pdpinch — APPROVED** [review]

**Pull request merged**
